In [1]:
import numpy as np

Задание 1

In [2]:
a = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание 2

In [3]:
a1 = a.reshape(3, 4)
a1


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a2 = a.reshape(4, 3)
a2


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [5]:
a3 = a.reshape(12, 1)
a3


array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [6]:
a4 = a.reshape(2, 6)
a4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
a5 = a.reshape(6,2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

Задание 3

In [8]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Задание 4. Думаю, что нет. Стобцы и строки это уже2 измерения.

Задание 5

In [23]:
a = np.random.randn(3, 4)
print(a)
print(a.flatten())

[[-1.23728271  0.33742908  0.22732884  0.04031066]
 [ 0.83851844 -1.43334417  0.88374866 -1.3189744 ]
 [-0.55973565  0.29298052 -0.56570093  1.8206275 ]]
[-1.23728271  0.33742908  0.22732884  0.04031066  0.83851844 -1.43334417
  0.88374866 -1.3189744  -0.55973565  0.29298052 -0.56570093  1.8206275 ]


Задание 6

In [32]:
c = np.arange(20, 0, -2)

print(c)

[20 18 16 14 12 10  8  6  4  2]


Задание 7

In [45]:
c = np.arange(20, 0, -2)
print(c.reshape(1, -1))

[[20 18 16 14 12 10  8  6  4  2]]


In [ ]:
Задание 8

In [55]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(c)
c.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

Задание 9

In [93]:
a = np.arange(1, 13)
A = a.reshape(4, 3)
B = A.dot(A.T)
print(B)
C = np.linalg.inv(B)
print(C)

[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
[[ 9.35339320e+13 -1.89435812e+12 -2.76813080e+14  1.85173506e+14]
 [-6.76285848e+14  7.89000156e+14  4.50857232e+14 -5.63571540e+14]
 [ 1.07196990e+15 -1.57231724e+15 -7.12752241e+13  5.71622562e+14]
 [-4.89217984e+14  7.85211439e+14 -1.02768928e+14 -1.93224528e+14]]


...а почему нет? :)

Задание 10

In [78]:
np.random.seed(seed=42)

Задание 11

In [83]:
c = np.random.randint(0, 16, (16))
print(c)

[ 4  0 11  9  5 12 11  8  0 10 10 14  9 15 11 11]


Задание 12

In [90]:
C = c.reshape(4, -1)
print(C)
D = B + C*10
print(D)

[[ 4  0 11  9]
 [ 5 12 11  8]
 [ 0 10 10 14]
 [ 9 15 11 11]]
[[ 54  32 160 158]
 [ 82 197 232 247]
 [ 50 222 294 406]
 [158 317 376 475]]


In [95]:
d = np.linalg.det(D)
print(d)

154521600.00000027


In [96]:
r = np.linalg.matrix_rank(D)
print(r)

4


In [97]:
D_inv = np.linalg.inv(D)

print(D_inv)

[[ 0.00278252 -0.01143801 -0.01168924  0.01501344]
 [-0.00955077  0.00901065 -0.00017913 -0.00135554]
 [ 0.00843196  0.01941851  0.00010665 -0.01299352]
 [-0.00122624 -0.01758007  0.00392333  0.00830136]]


Задание 13

In [121]:
T = (D_inv > 0)
print(T)

N = np.zeros((4, 4))
for i in range(len(T)):
    for j in range(len(T[i])):
        if T[i][j] == True:
            N[i][j] = 1
        else:
            N[i][j] = 0
print(N)

[[ True False False  True]
 [False  True False False]
 [ True  True  True False]
 [False False  True  True]]
[[1. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 1. 1. 0.]
 [0. 0. 1. 1.]]


In [128]:
ind0 = np.where(N == 0)
print(ind0)
ind1 = np.where(N == 1)
print(ind1)

# Как сделать дальше, не  понимаю :(
# Написал обычным питоном

E = np.zeros((4, 4))
for i in range(len(E)):
    for j in range(len(E[i])):
        if N[i][j] == 1:
            E[i][j] = B[i][j]
        else:
            E[i][j] = C[i][j]
            
print(E)

(array([0, 0, 1, 1, 1, 2, 3, 3]), array([1, 2, 0, 2, 3, 3, 0, 1]))
(array([0, 0, 1, 2, 2, 2, 3, 3]), array([0, 3, 1, 0, 1, 2, 2, 3]))
[[ 1.40000000e+01 -1.89435812e+12 -2.76813080e+14  6.80000000e+01]
 [-6.76285848e+14  7.70000000e+01  4.50857232e+14 -5.63571540e+14]
 [ 5.00000000e+01  1.22000000e+02  1.94000000e+02  5.71622562e+14]
 [-4.89217984e+14  7.85211439e+14  2.66000000e+02  3.65000000e+02]]
